# Generated by Django 3.0.2 on 2020-02-04 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('look', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=100)),
                ('image', models.FileField(upload_to='photos')),
            ],
        ),
    ]
