# Generated by Django 3.0.2 on 2020-02-06 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('look', '0002_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='adress',
            new_name='adres',
        ),
    ]
