# Generated by Django 3.0.2 on 2020-02-07 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('look', '0003_auto_20200206_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='image',
            field=models.ImageField(upload_to='photos'),
        ),
    ]
