# Generated by Django 3.0.3 on 2020-02-24 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('look', '0004_auto_20200207_0805'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='media')),
                ('section', models.CharField(choices=[('logo', 'logo'), ('href', 'odnośnik'), ('image', 'zdjęcie')], max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='File',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='adres',
            new_name='adress',
        ),
        migrations.AlterField(
            model_name='contact',
            name='number',
            field=models.CharField(default=48513294634, max_length=12),
        ),
    ]
