# Generated by Django 3.0.3 on 2020-02-24 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('look', '0005_auto_20200224_0959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='number',
        ),
    ]
