# Generated by Django 3.0.2 on 2020-02-24 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('look', '0006_remove_image_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='section',
            field=models.CharField(choices=[('bathroom', 'łazienka'), ('kitchen', 'kuchnia'), ('closet', 'szafy'), ('beds', 'łóżka'), ('other', 'inne')], max_length=100),
        ),
    ]
