# Generated by Django 3.0.3 on 2020-02-25 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('look', '0007_auto_20200224_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='description',
            field=models.CharField(default='Ah ta jakość', max_length=3000),
        ),
    ]
