# Generated by Django 3.0.3 on 2020-02-26 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('look', '0008_image_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='section',
            field=models.CharField(choices=[('bathroom', 'łazienka'), ('kitchen', 'kuchnia'), ('closet', 'szafy'), ('beds', 'łóżka'), ('other', 'inne'), ('back', 'zaplecze')], max_length=100),
        ),
    ]
